### PR TITLE
systemd: v233 -> v234

### PR DESCRIPTION
**Pull request by Mic92**
Continuous integration branch  for upcoming systemd v234 (wrong target branch as I cannot open a pull request towards NixOS:nixos-v234)

NEWS: https://github.com/systemd/systemd/blob/v234/NEWS

Notable new features/changes:
- systemd-logind can be restarted without loosing state
- new build system `meson` might replace `autotools` in a few versions. This would introduce a python dependency in our chain: systemd -> util-linux -> quite a few packages.

Notable changes from my site: 
-  timedated: allow setting timezone (thanks @lheckemann)
- Revert "Get rid of ExecStart=agetty lines" (more a aesthetically change and a reminder to update agetty modules, when merging systemd upgrade into nixpkgs)

### CODE REVIEW

**Comment by 0xABAB** [comment]
Before anyone is supposed to review this, this situation with a 20K line diff will be fixed, right?

**Comment by Mic92** [comment]
yes, I cannot create a pull request against `nixos-v234`, which does not exists yet.

**Comment by globin** [comment]
feel free to ping me when this is ready (better on IRC, but here should be fine, too)

**Comment by lheckemann** [comment]
So, v234 is now out. So I'm guessing we should rebase and get a nixos-v234 branch made out of this now?

**Comment by Mic92** [comment]
ping @globin

**Comment by globin** [comment]
Pushed this to nixos-v234 and pushed the systemd update to staging in: NixOS/nixpkgs@ae26f29

**Comment by Mic92** [comment]
@globin I have also added https://github.com/NixOS/nixpkgs/commit/c2cf696430055498467dd9deec59939e8d52a43e to staging. There are some changes upstream added to agetty.service, we should consider applying to nixos as well. But at the moment the old approach is ok.

**Pull request closed without merging**
