### PR TITLE
systemd: 238 -> 239

### PR DESCRIPTION
**Pull request by Mic92**
DO NOT MERGE YET.

Status:
- works for me
- user-runtime-dir@.service needs to be installed in our nixos module -> I will make a pull request for that.
- we should take a look if interface renaming still works, there were updates in systemd-udevd for net-id builtin

### CODE REVIEW

**Comment by Mic92** [comment]
I tested this on my machine. @fpletz or @globin please merge this, then I will iterate over the tests.

**Comment by fpletz** [comment]
Pushed to https://github.com/NixOS/systemd/tree/nixos-v239. Thanks!

**Comment by dtzWill** [comment]
The note in systemd's default.nix says to follow stable, "not development".  Is a stable v239 expected soon?

**Comment by Mic92** [comment]
@dtzWill systemd-stable is just meant to be for backports that happen after the release. There seems no such backports yet for v239 either required or nobody has bothered doing so. The version v239 is already released though.

**Pull request closed without merging**
