### PR TITLE
Fix mount option `x-initrd.mount` handling (#35268)

### PR DESCRIPTION
**Pull request by ghost**
This will fix issue https://github.com/NixOS/nixpkgs/issues/35268.

### CODE REVIEW

**Comment by edolstra** [comment]
Thanks!

**Comment by edolstra** [comment]
Do we actually still need the check for `/nix` and `/nix/store` in `mount_is_extrinsic()`? Don't they get marked as provided by the initrd automatically?

**Comment by ghost** [comment]
> Do we actually still need the check for /nix and /nix/store in mount_is_extrinsic()?

There are two ways: either we check them in `mount_is_extrinsic`, or we add `x-initrd.mount` mount option to them.

> Don't they get marked as provided by the initrd automatically?

Unfortunately, they do not.

**Pull request merged**
