### PR TITLE
nspawn: wait for network namespace creation before interface setup (#8633)

### PR DESCRIPTION
**Pull request by xeji**
Upstream fix for container networking problems with systemd 238 and kernel 4.14.
This will fix https://github.com/NixOS/nixpkgs/issues/38341 
/cc @vcunat

### CODE REVIEW

**Comment by shlevy** [comment]
@xeji If this is a straightforward cherry-pick, can you generate it with `git cherry-pick -x`?

**Comment by xeji** [comment]
done

**Comment by xeji** [comment]
@shlevy what's the process for upgrading systemd 238 in nixpkgs? Should I make a PR to bump the revision in staging?

**Comment by shlevy** [comment]
I think so, yeah.

**Comment by shlevy** [comment]
Also probably should make a cherry-pick PR to staging-18.03

**Comment by xeji** [comment]
will do

**Pull request merged**
